import React, { useState } from "react";
import {
  FileText,
  Download,
  Printer,
  Copy,
  Check,
  ShieldCheck,
  AlertOctagon,
  CheckCircle2,
  ExternalLink,
  Code,
  Sparkles,
} from "lucide-react";
import { ReportResult, Task } from "../types.js";
import { useTranslation } from "../i18n.js";

interface ReportViewProps {
  report: ReportResult | null;
  task: Task;
}

export const ReportView: React.FC<ReportViewProps> = ({ report, task }) => {
  const { t, language } = useTranslation();
  const [copied, setCopied] = useState(false);

  if (!report) {
    return (
      <div className="p-16 rounded-2xl bg-[#fdfaf3] border border-[#dfd6bf] text-center space-y-3 shadow-sm">
        <FileText className="w-10 h-10 text-[#839496] mx-auto" />
        <h3 className="text-base font-bold text-[#2b3638]">
          {language === "zh" ? "尚未生成安全审计报告" : "No Report Generated Yet"}
        </h3>
        <p className="text-xs text-[#586e75] max-w-md mx-auto">
          {language === "zh"
            ? "请点击顶部「启动自主挖掘流水线」执行完整审计，ReportAgent 将汇总确认的漏洞、统计指标和证据链自动生成报告。"
            : "Execute the multi-agent pipeline on the target. The ReportAgent will aggregate confirmed findings, metrics, and evidence."}
        </p>
      </div>
    );
  }

  const { content } = report;
  const reportFindings = content.findings.map((item) => item.finding);
  const recommendations = Array.from(
    new Set(content.findings.flatMap((item) => item.remediation.guidance)),
  );
  const counts = content.risk_summary.counts;
  const humanReview = content.human_review;
  const acceptanceSummary = content.course_acceptance_summary;
  const acceptanceBatches = content.acceptance_batches || [];
  const llmScan = content.llm_vulnerability_scan;
  const binaryProtection = content.binary_protection_analysis;
  const softwareCode = content.software_code_security;

  const handleCopyMarkdown = () => {
    const md = `# VulnAgent Multi-Agent Security Audit Report
**Task ID:** ${report.task_id}
**Target:** ${content.task.target.path} (${content.task.target.target_type})
**Generated By:** ${String(report.metadata?.generator || "StructuredReportGenerator v0.4")}
**Date:** ${new Date().toISOString()}
**Compliance:** ${content.compliance_notice || "仅用于安全审计与防御研究，仅限教学实验使用"}

## Executive Summary
${content.risk_summary.headline}

## Risk Metrics
- Total Candidates Evaluated: ${counts.total}
- Confirmed Vulnerabilities: ${counts.confirmed}
- False Positives Rejected: ${counts.rejected}
- Evidences Linked: ${content.summary.evidence_count}

## Confirmed Findings
${reportFindings.map((f) => `### ${f.title} (${f.cwe_id || "CWE"}) - ${f.severity}\n${f.description}\n`).join("\n") || "None"}

## Strategic Recommendations
${recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n") || "No generated remediation guidance."}

${binaryProtection ? `## Binary Program Protection Analysis
- Protection: ${binaryProtection.protection?.family || "unclassified"} (level ${binaryProtection.protection?.level || 0})
- Restoration: ${binaryProtection.restoration.status}; success=${Boolean(binaryProtection.restoration.success)}
- Parseable: ${Boolean(binaryProtection.restoration.validation?.parseable)}
- Readability: ${binaryProtection.deobfuscation.readability?.before || 0} -> ${binaryProtection.deobfuscation.readability?.after || 0}
` : ""}

${softwareCode ? `## 大模型服务代码安全审计
- Code findings: ${softwareCode.finding_count}
- Severity: critical ${softwareCode.risk_level_distribution.CRITICAL || 0}, high ${softwareCode.risk_level_distribution.HIGH || 0}, medium ${softwareCode.risk_level_distribution.MEDIUM || 0}, low ${softwareCode.risk_level_distribution.LOW || 0}

${softwareCode.dossiers.map((item) => `### ${item.title}
Type: ${item.vulnerability_type}; Severity: ${item.risk_level}; Status: ${item.status}
Location: ${item.source_location?.file_path || "N/A"}:${item.source_location?.line_start || "?"}
Evidence chain: ${item.evidence_chain.map((evidence) => String(evidence.stage)).join(" → ") || "pending"}
Remediation: ${String(item.agent_assessment?.remediation_summary || item.remediation.priority_label || "人工复核后加固")}`).join("\n\n")}

${softwareCode.compliance_notice}` : ""}

${llmScan ? `## Local Ollama LLM Vulnerability Scan
- Model: ${llmScan.model_name}
- Method: ${llmScan.method}
- Cases: ${llmScan.summary.completed_cases}/${llmScan.summary.total_cases}
- Triggered: ${llmScan.summary.triggered_count}
- Severity: high ${llmScan.summary.by_severity.high || 0}, medium ${llmScan.summary.by_severity.medium || 0}, low ${llmScan.summary.by_severity.low || 0}
- Prompt injection: ${llmScan.summary.by_vulnerability_type.prompt_injection || 0}
- System prompt leakage: ${llmScan.summary.by_vulnerability_type.system_prompt_leakage || 0}
- Safety alignment bypass: ${llmScan.summary.by_vulnerability_type.safety_alignment_bypass || 0}

${llmScan.probe_results.map((item) => `### ${item.case_id} · ${item.title}
Verdict: ${item.verdict}; Severity: ${item.severity}; SHA-256: ${item.response_sha256}

${item.decision_basis}`).join("\n\n")}` : ""}

## Human Review
${humanReview?.annotations.map((item) => `- ${item.vulnerability_id}: ${item.decision} — ${item.note || "No note"}`).join("\n") || "No human review annotations."}

## Course Acceptance Matrix
${acceptanceSummary?.groups.map((group) => `- ${group.group_id.toUpperCase()}: ${group.status} — ${group.summary}`).join("\n") || "Acceptance matrix unavailable."}

## Linked Custom Acceptance Batches
${acceptanceBatches.map((batch) => `- ${batch.batch_id}: execution ${batch.completed_groups}/${batch.total_groups} — ${batch.name}`).join("\n") || "This task is not linked to a custom acceptance batch."}
`;
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJson = () => {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `VulnAgent-Audit-${report.task_id}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      {/* Action Header */}
      <div className="p-5 rounded-2xl bg-[#f4eedb] border border-[#dfd6bf] shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <div className="w-6 h-6 rounded-lg bg-[#2aa198]/10 border border-[#2aa198]/30 flex items-center justify-center text-[#2aa198]">
              <FileText className="w-3.5 h-3.5" />
            </div>
            <h2 className="text-base font-bold text-[#2b3638]">{t("repTitle")}</h2>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-[#edf5d3] text-[#859900] border border-[#cce38d] font-semibold">
              Generated by ReportAgent
            </span>
          </div>
          <p className="text-xs text-[#586e75]">
            {t("repSubtitle")}
          </p>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={handleCopyMarkdown}
            className="px-3 py-1.5 rounded-lg bg-[#f5eed9] hover:bg-[#eee8d5] border border-[#dfd6bf] text-xs font-mono text-[#586e75] flex items-center gap-1.5 transition-colors cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-[#859900]" /> : <Copy className="w-3.5 h-3.5 text-[#2aa198]" />}
            <span>{copied ? (language === "zh" ? "已复制 Markdown" : "Copied Markdown") : (language === "zh" ? "复制 MD" : "Copy MD")}</span>
          </button>
          <a
            href={`/api/tasks/${report.task_id}/report.html`}
            target="_blank"
            rel="noreferrer"
            className="px-3 py-1.5 rounded-lg bg-[#eef4fb] hover:bg-[#e2eef9] border border-[#b9d6f3] text-xs font-semibold text-[#268bd2] flex items-center gap-1.5 transition-colors"
          >
            <Code className="w-3.5 h-3.5" />
            <span>{language === "zh" ? "打开 HTML" : "Open HTML"}</span>
            <ExternalLink className="w-3 h-3" />
          </a>
          <a
            href={`/api/tasks/${report.task_id}/report.pdf`}
            download={`VulnAgent-Audit-${report.task_id}.pdf`}
            className="px-3 py-1.5 rounded-lg bg-[#f5eed9] hover:bg-[#eee8d5] border border-[#dfd6bf] text-xs font-semibold text-[#586e75] flex items-center gap-1.5 transition-colors"
          >
            <Printer className="w-3.5 h-3.5 text-[#6c71c4]" />
            <span>{language === "zh" ? "下载 PDF" : "Download PDF"}</span>
          </a>
          <button
            onClick={handleDownloadJson}
            className="px-3 py-1.5 rounded-lg bg-[#2aa198] hover:bg-[#238b83] text-white text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer shadow-xs"
          >
            <Download className="w-3.5 h-3.5" />
            <span>{t("repExportJson")}</span>
          </button>
        </div>
      </div>

      {/* Formal Printable Document Layout */}
      <div className="p-8 sm:p-10 rounded-2xl bg-[#fdfaf3] border border-[#dfd6bf] shadow-sm space-y-8 font-sans">
        {/* Document Title Header */}
        <div className="border-b border-[#dfd6bf] pb-6 flex flex-col sm:flex-row sm:items-end justify-between gap-4">
          <div>
            <span className="text-xs font-mono text-[#2aa198] uppercase tracking-wider font-semibold">
              VULNAGENT AUTONOMOUS SECURITY AUDIT
            </span>
            <h1 className="text-2xl font-bold text-[#2b3638] mt-1">
              {language === "zh" ? "软件安全审计与漏洞挖掘总报告" : "Audit Findings & Risk Assessment"}
            </h1>
            <p className="text-xs text-[#586e75] mt-1 font-mono">
              {language === "zh" ? "审计目标: " : "Target: "}<span className="text-[#2b3638] font-medium">{content.task.target.path || task.target.path}</span>
            </p>
            <p className="mt-2 text-[11px] font-semibold text-[#b58900]">{content.compliance_notice || "仅用于安全审计与防御研究，仅限教学实验使用"}</p>
          </div>

          <div className="text-left sm:text-right font-mono text-xs text-[#586e75]">
            <div>{language === "zh" ? "任务 ID: " : "Task: "}<span className="text-[#2aa198] font-semibold">{report.task_id}</span></div>
            <div>{language === "zh" ? "生成日期: " : "Generated: "}{new Date().toLocaleDateString()}</div>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold text-[#2b3638] uppercase tracking-wider font-mono flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-[#2aa198]" />
            {t("repExecutiveSummary")}
          </h3>
          <div className="p-5 rounded-xl bg-[#f5eed9] border border-[#dfd6bf] text-sm text-[#2b3638] leading-relaxed">
            {content.risk_summary.headline}
          </div>
        </div>

        {/* Severity & Metrics Scoreboard */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="p-4 rounded-xl bg-[#f5eed9] border border-[#dfd6bf]">
            <span className="text-[10px] uppercase font-mono text-[#586e75] block">
              {language === "zh" ? "评估候选总数" : "Total Evaluated"}
            </span>
            <span className="text-2xl font-bold font-mono text-[#2b3638] mt-1 block">
              {counts.total}
            </span>
          </div>
          <div className="p-4 rounded-xl bg-[#fce8e6] border border-[#f5b8b5]">
            <span className="text-[10px] uppercase font-mono text-[#dc322f] block">
              {language === "zh" ? "独立复核确认" : "Independently Confirmed"}
            </span>
            <span className="text-2xl font-bold font-mono text-[#dc322f] mt-1 block">
              {counts.confirmed}
            </span>
          </div>
          <div className="p-4 rounded-xl bg-[#edf5d3] border border-[#cce38d]">
            <span className="text-[10px] uppercase font-mono text-[#859900] block">
              {language === "zh" ? "复核剔除误报" : "False Positives Filtered"}
            </span>
            <span className="text-2xl font-bold font-mono text-[#859900] mt-1 block">
              {counts.rejected}
            </span>
          </div>
          <div className="p-4 rounded-xl bg-[#eef7f6] border border-[#bfe3e0]">
            <span className="text-[10px] uppercase font-mono text-[#2aa198] block">
              {language === "zh" ? "关联证据记录" : "Linked Evidence Records"}
            </span>
            <span className="text-2xl font-bold font-mono text-[#2aa198] mt-1 block">
              {content.summary.evidence_count}
            </span>
          </div>
        </div>

        {llmScan && (
          <section className="space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-2">
              <div>
                <div className="text-[10px] uppercase tracking-[0.18em] font-mono text-[#2aa198] font-bold">LOCAL OLLAMA · SYNTHETIC CANARY</div>
                <h3 className="text-sm font-bold text-[#2b3638] mt-1">
                  {language === "zh" ? "开源大模型漏洞扫描结果" : "Open-source LLM vulnerability scan"}
                </h3>
              </div>
              <span className="text-[11px] font-mono text-[#586e75]">{llmScan.model_name} · {llmScan.scan_id}</span>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-5 gap-2.5">
              {[
                [language === "zh" ? "用例" : "Cases", llmScan.summary.total_cases, "text-[#2b3638]"],
                [language === "zh" ? "触发" : "Triggered", llmScan.summary.triggered_count, "text-[#dc322f]"],
                [language === "zh" ? "高危" : "High", llmScan.summary.by_severity.high || 0, "text-[#dc322f]"],
                [language === "zh" ? "中危" : "Medium", llmScan.summary.by_severity.medium || 0, "text-[#b58900]"],
                [language === "zh" ? "低危" : "Low", llmScan.summary.by_severity.low || 0, "text-[#2aa198]"],
              ].map(([label, value, color]) => (
                <div key={String(label)} className="rounded-xl bg-[#f5eed9] border border-[#dfd6bf] p-3">
                  <div className="text-[10px] uppercase font-mono text-[#657b83]">{label}</div>
                  <div className={`text-xl font-black font-mono mt-1 ${color}`}>{value}</div>
                </div>
              ))}
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">
              {[
                [language === "zh" ? "提示词注入" : "Prompt injection", llmScan.summary.by_vulnerability_type.prompt_injection || 0],
                [language === "zh" ? "系统提示词泄露" : "System prompt leakage", llmScan.summary.by_vulnerability_type.system_prompt_leakage || 0],
                [language === "zh" ? "安全对齐绕过" : "Safety alignment bypass", llmScan.summary.by_vulnerability_type.safety_alignment_bypass || 0],
              ].map(([label, value]) => (
                <div key={String(label)} className="rounded-lg bg-[#eef7f6] border border-[#bfe3e0] px-3 py-2 text-xs flex items-center justify-between">
                  <span className="text-[#586e75]">{label}</span><strong className="font-mono text-[#2aa198]">{value}</strong>
                </div>
              ))}
            </div>
            <div className="space-y-2">
              {llmScan.probe_results.filter((item) => item.verdict === "triggered").map((item) => (
                <details key={item.case_id} className="rounded-xl bg-[#fcf8ed] border border-[#dfd6bf] p-3 text-xs">
                  <summary className="cursor-pointer font-bold text-[#2b3638] flex items-center gap-2">
                    <span className="font-mono text-[#dc322f]">{item.severity.toUpperCase()}</span>
                    {item.case_id} · {item.title}
                  </summary>
                  <div className="mt-3 space-y-2 text-[#586e75] leading-relaxed">
                    <p>{item.decision_basis}</p>
                    <div className="font-mono text-[10px] break-all">SHA-256 › {item.response_sha256}</div>
                    <div className="text-[10px] text-[#839496]">{language === "zh" ? "测试输入和原始响应不在报告界面展示。" : "Test inputs and raw responses are not displayed."}</div>
                  </div>
                </details>
              ))}
            </div>
            <p className="text-[11px] text-[#657b83] leading-relaxed border-l-2 border-[#2aa198] pl-3">{llmScan.formal_verdict_note}</p>
          </section>
        )}

        {binaryProtection && (
          <section className="rounded-xl border border-[#bfe3e0] bg-[#eef7f6] p-5">
            <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <h3 className="text-sm font-bold text-[#2b3638] uppercase tracking-wider font-mono flex items-center gap-2">
                  <ShieldCheck className="h-4 w-4 text-[#2aa198]" />
                  {binaryProtection.title}
                </h3>
                <p className="mt-1 text-xs text-[#586e75]">
                  {binaryProtection.protection?.family || (language === "zh" ? "未归因保护器" : "Unclassified protector")}
                  {binaryProtection.protection ? ` · L${binaryProtection.protection.level} · ${Math.round(Number(binaryProtection.protection.confidence || 0) * 100)}%` : ""}
                </p>
              </div>
              <span className={`rounded-full border px-2.5 py-1 text-[10px] font-mono font-bold ${binaryProtection.restoration.success ? "border-[#cce38d] bg-[#edf5d3] text-[#657b00]" : "border-[#ecd8a6] bg-[#fbf4e6] text-[#b58900]"}`}>
                {binaryProtection.restoration.success ? (language === "zh" ? "还原并校验" : "RESTORED + VALIDATED") : (language === "zh" ? "识别/策略完成" : "ANALYSIS ONLY")}
              </span>
            </div>
            <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">
              {[
                [language === "zh" ? "可解析" : "Parseable", binaryProtection.restoration.validation?.parseable ? "YES" : "NO"],
                [language === "zh" ? "导入符号" : "Imports", binaryProtection.restoration.validation?.imports ?? 0],
                [language === "zh" ? "还原耗时" : "Elapsed", `${binaryProtection.restoration.metrics?.elapsed_ms ?? 0} ms`],
                [language === "zh" ? "代码可读性" : "Readability", `${binaryProtection.deobfuscation.readability?.before || 0}→${binaryProtection.deobfuscation.readability?.after || 0}`],
              ].map(([label, value]) => (
                <div key={String(label)} className="rounded-lg border border-[#bfe3e0] bg-white/80 p-3">
                  <div className="text-[10px] font-mono text-[#657b83]">{label}</div>
                  <div className="mt-1 text-base font-black text-[#147f79]">{String(value)}</div>
                </div>
              ))}
            </div>
            <div className="mt-4 flex flex-wrap items-center gap-1.5">
              {binaryProtection.evidence_chain.map((item, index) => (
                <React.Fragment key={String(item.evidence_id)}>
                  {index > 0 && <span className="text-[#93a1a1]">→</span>}
                  <span className="rounded border border-[#bfe3e0] bg-white px-2 py-1 text-[10px] font-mono text-[#147f79]">{String(item.stage)}</span>
                </React.Fragment>
              ))}
            </div>
          </section>
        )}

        {softwareCode && softwareCode.finding_count > 0 && (
          <section className="rounded-xl border border-[#c8c0dc] bg-[#f3f0fa] p-5 space-y-4">
            <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <div className="text-[10px] uppercase tracking-[0.18em] font-mono text-[#6c71c4] font-bold">SOFTWARE CODE SECURITY</div>
                <h3 className="mt-1 text-sm font-bold text-[#2b3638]">{softwareCode.title}</h3>
              </div>
              <span className="rounded-full border border-[#c8c0dc] bg-white px-3 py-1 text-[10px] font-mono text-[#6c71c4]">{softwareCode.finding_count} FINDINGS</span>
            </div>
            <div className="grid grid-cols-4 gap-2">
              {["CRITICAL", "HIGH", "MEDIUM", "LOW"].map((level) => (
                <div key={level} className="rounded-lg border border-[#d9d3e7] bg-white/80 p-2.5">
                  <div className="text-[9px] font-mono text-[#657b83]">{level}</div>
                  <div className="mt-1 text-lg font-black font-mono text-[#6c71c4]">{softwareCode.risk_level_distribution[level] || 0}</div>
                </div>
              ))}
            </div>
            <div className="space-y-3">
              {softwareCode.dossiers.map((dossier) => (
                <article key={dossier.dossier_id} className="rounded-xl border border-[#d9d3e7] bg-[#fdfaf3] p-4 text-xs">
                  <div className="flex flex-wrap items-start justify-between gap-2">
                    <div><strong className="text-[#2b3638]">{dossier.title}</strong><div className="mt-1 font-mono text-[10px] text-[#6c71c4]">{dossier.vulnerability_type} · {dossier.cwe_id || "CWE N/A"}</div></div>
                    <span className="rounded border border-[#c8c0dc] px-2 py-1 font-mono text-[10px] text-[#6c71c4]">{dossier.risk_level} · {dossier.status}</span>
                  </div>
                  <div className="mt-3 grid gap-2 sm:grid-cols-3">
                    <div className="rounded-lg bg-[#f5eed9] p-2"><b>{language === "zh" ? "源码定位" : "Source"}</b><div className="mt-1 break-all font-mono text-[10px]">{dossier.source_location?.file_path || "N/A"}:{dossier.source_location?.line_start || "?"}</div></div>
                    <div className="rounded-lg bg-[#f5eed9] p-2"><b>{language === "zh" ? "路径证据" : "Path evidence"}</b><div className="mt-1 text-[10px]">CFG {dossier.control_flow_path.length} · Taint {dossier.taint_path.length}</div></div>
                    <div className="rounded-lg bg-[#f5eed9] p-2"><b>{language === "zh" ? "受控验证" : "Validation"}</b><div className="mt-1 text-[10px]">{dossier.dynamic_validation ? `${dossier.dynamic_validation.case_count || 0} cases · ${dossier.dynamic_validation.anomaly_count || 0} anomalies` : (language === "zh" ? "未执行" : "Not run")}</div></div>
                  </div>
                  <p className="mt-3 text-[#586e75]">{String(dossier.agent_assessment?.summary || (language === "zh" ? "等待智能体研判证据" : "Agent assessment pending"))}</p>
                  <p className="mt-2 text-[#2b3638]"><b>{language === "zh" ? "修复方向：" : "Remediation: "}</b>{String(dossier.agent_assessment?.remediation_summary || dossier.remediation.priority_label || "—")}</p>
                  <div className="mt-3 flex flex-wrap items-center gap-1">
                    {dossier.evidence_chain.map((item, index) => <React.Fragment key={`${String(item.evidence_id)}-${index}`}>{index > 0 && <span className="text-[#93a1a1]">→</span>}<span className="rounded border border-[#d9d3e7] bg-white px-2 py-1 text-[9px] font-mono text-[#6c71c4]">{String(item.stage)}</span></React.Fragment>)}
                  </div>
                </article>
              ))}
            </div>
            <p className="text-[10px] font-semibold text-[#6c71c4]">{softwareCode.compliance_notice}</p>
          </section>
        )}

        {humanReview && (
          <section className="p-4 rounded-xl bg-[#f5eed9] border border-[#dfd6bf]">
            <h3 className="text-xs font-bold text-[#2b3638] uppercase tracking-wider font-mono">
              {language === "zh" ? "人工复核标注" : "Human Review"} · {humanReview.annotation_count}
            </h3>
            <div className="mt-3 space-y-2">
              {humanReview.annotations.length ? humanReview.annotations.map((item) => (
                <div key={item.annotation_id} className="rounded-lg bg-[#fdfaf3] border border-[#dfd6bf] px-3 py-2 text-xs">
                  <div className="font-mono text-[#6c71c4] font-bold">{item.decision.toUpperCase()} · {item.vulnerability_id}</div>
                  <p className="text-[#586e75] mt-1">{item.note || (language === "zh" ? "未填写备注" : "No note")}</p>
                </div>
              )) : <p className="text-xs text-[#839496]">{language === "zh" ? "尚无人工标注。" : "No human annotations yet."}</p>}
            </div>
          </section>
        )}

        {acceptanceBatches.length > 0 && (
          <section className="p-4 rounded-xl bg-[#eef4fb] border border-[#b9d6f3]">
            <h3 className="text-xs font-bold text-[#2b3638] uppercase tracking-wider font-mono flex items-center gap-2">
              <CheckCircle2 className="w-3.5 h-3.5 text-[#268bd2]" />
              {language === "zh" ? "关联的自定义验收批次" : "Linked custom acceptance batches"}
            </h3>
            <div className="mt-3 space-y-3">
              {acceptanceBatches.map((batch) => (
                <div key={batch.batch_id} className="rounded-lg bg-[#fdfaf3] border border-[#dfd6bf] p-3 text-xs">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                    <div>
                      <strong className="text-[#2b3638]">{batch.name}</strong>
                      <div className="font-mono text-[10px] text-[#268bd2] mt-0.5">{batch.batch_id}</div>
                    </div>
                    <span className={`px-2 py-0.5 rounded border text-[10px] font-mono font-bold ${batch.state === "completed" ? "bg-[#edf5d3] border-[#cce38d] text-[#657b00]" : "bg-[#fbf4e6] border-[#ecd8a6] text-[#b58900]"}`}>
                      EXECUTION {batch.completed_groups}/{batch.total_groups}
                    </span>
                  </div>
                  <div className="mt-2 grid grid-cols-1 sm:grid-cols-3 gap-1.5">
                    {batch.groups.map((group) => (
                      <div key={group.group_id} className="rounded bg-[#f5eed9] border border-[#dfd6bf] px-2 py-1.5">
                        <span className="font-mono font-bold text-[#2aa198]">{group.group_id.toUpperCase()}</span>
                        <span className="text-[#586e75] ml-1.5">{group.completed_count}/{group.selected_count}</span>
                      </div>
                    ))}
                  </div>
                  <p className="mt-2 text-[10px] text-[#839496]">{batch.metric_note}</p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Confirmed Findings Section */}
        <div className="space-y-4">
          <h3 className="text-sm font-bold text-[#2b3638] uppercase tracking-wider font-mono flex items-center gap-2">
            <AlertOctagon className="w-4 h-4 text-[#dc322f]" />
            {t("repConfirmedFindings")}
          </h3>

          <div className="space-y-4">
            {content.findings.map(({ finding: f, verification }) => (
              <div
                key={f.vulnerability_id}
                className="p-5 rounded-xl bg-[#fcf8ed] border border-[#dfd6bf] space-y-3 shadow-2xs"
              >
                <div className="flex items-center justify-between gap-2 flex-wrap">
                  <div className="flex items-center gap-2">
                    <span className="px-2 py-0.5 rounded text-xs font-mono font-bold bg-[#fce8e6] text-[#dc322f] border border-[#f5b8b5]">
                      {f.severity || "CRITICAL"}
                    </span>
                    <span className="text-sm font-bold text-[#2b3638]">{f.title}</span>
                  </div>
                  <span className="font-mono text-xs text-[#2aa198] font-semibold">{f.cwe_id}</span>
                </div>

                <p className="text-xs text-[#586e75] leading-relaxed">{f.description}</p>

                {verification && (
                  <div className="text-xs bg-[#eef7f6] border border-[#bfe3e0] rounded-lg p-3 space-y-1">
                    <div className="font-mono text-[#2aa198] font-semibold">
                      Verification: {verification.status.toUpperCase()} · {Math.round(verification.confidence * 100)}%
                    </div>
                    <p className="text-[#586e75] leading-relaxed">{verification.rationale}</p>
                  </div>
                )}

                {f.location && (
                  <div className="text-xs font-mono text-[#586e75] bg-[#f5eed9] p-2.5 rounded-lg border border-[#dfd6bf]">
                    {language === "zh" ? "证据位置: " : "Evidence location: "}
                    <span className="text-[#2b3638] font-medium">
                      {f.location.file_path
                        ? `${f.location.file_path}:${f.location.line_start ?? "?"}-${f.location.line_end ?? "?"}`
                        : [
                            f.location.module_name,
                            f.location.binary_address ? `VA ${f.location.binary_address}` : null,
                            f.metadata?.binary_file_offset ? `file+${f.metadata.binary_file_offset}` : null,
                          ].filter(Boolean).join(" · ") || "N/A"}
                    </span>
                    {f.location.function_name && <span> (fn: {f.location.function_name})</span>}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Strategic Remediation Section */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold text-[#2b3638] uppercase tracking-wider font-mono flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-[#859900]" />
            {t("repRemediationTitle")}
          </h3>

          <div className="space-y-2">
            {(recommendations.length ? recommendations : [
              language === "zh" ? "当前报告没有生成额外修复建议。" : "No additional remediation guidance was generated.",
            ]).map((rec, idx) => (
              <div
                key={idx}
                className="p-3.5 rounded-xl bg-[#f5eed9] border border-[#dfd6bf] flex items-start gap-3 text-xs text-[#2b3638] font-mono"
              >
                <span className="w-5 h-5 rounded-md bg-[#edf5d3] text-[#859900] border border-[#cce38d] flex items-center justify-center shrink-0 text-[11px] font-bold">
                  {idx + 1}
                </span>
                <span className="leading-relaxed">{rec}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
