import React, { useState } from "react";
import {
  FileText,
  Download,
  Printer,
  Copy,
  Check,
  ShieldCheck,
  AlertOctagon,
  CheckCircle2,
  ExternalLink,
  Code,
  Sparkles,
} from "lucide-react";
import { ReportResult, Task } from "../types.js";
import { useTranslation } from "../i18n.js";

interface ReportViewProps {
  report: ReportResult | null;
  task: Task;
}

export const ReportView: React.FC<ReportViewProps> = ({ report, task }) => {
  const { t, language } = useTranslation();
  const [copied, setCopied] = useState(false);

  if (!report) {
    return (
      <div className="p-16 rounded-2xl bg-[#fdfaf3] border border-[#dfd6bf] text-center space-y-3 shadow-sm">
        <FileText className="w-10 h-10 text-[#839496] mx-auto" />
        <h3 className="text-base font-bold text-[#2b3638]">
          {language === "zh" ? "尚未生成安全审计报告" : "No Report Generated Yet"}
        </h3>
        <p className="text-xs text-[#586e75] max-w-md mx-auto">
          {language === "zh"
            ? "请点击顶部「启动自主挖掘流水线」执行完整审计，ReportAgent 将汇总确认的漏洞、统计指标和证据链自动生成报告。"
            : "Execute the multi-agent pipeline on the target. The ReportAgent will aggregate confirmed findings, metrics, and evidence."}
        </p>
      </div>
    );
  }

  const { content } = report;
  const reportFindings = content.findings.map((item) => item.finding);
  const recommendations = Array.from(
    new Set(content.findings.flatMap((item) => item.remediation.guidance)),
  );
  const counts = content.risk_summary.counts;

  const handleCopyMarkdown = () => {
    const md = `# VulnAgent Multi-Agent Security Audit Report
**Task ID:** ${report.task_id}
**Target:** ${content.task.target.path} (${content.task.target.target_type})
**Generated By:** ${String(report.metadata?.generator || "StructuredReportGenerator v0.3")}
**Date:** ${new Date().toISOString()}

## Executive Summary
${content.risk_summary.headline}

## Risk Metrics
- Total Candidates Evaluated: ${counts.total}
- Confirmed Vulnerabilities: ${counts.confirmed}
- False Positives Rejected: ${counts.rejected}
- Evidences Linked: ${content.summary.evidence_count}

## Confirmed Findings
${reportFindings.map((f) => `### ${f.title} (${f.cwe_id || "CWE"}) - ${f.severity}\n${f.description}\n`).join("\n") || "None"}

## Strategic Recommendations
${recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n") || "No generated remediation guidance."}
`;
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJson = () => {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `VulnAgent-Audit-${report.task_id}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      {/* Action Header */}
      <div className="p-5 rounded-2xl bg-[#f4eedb] border border-[#dfd6bf] shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <div className="w-6 h-6 rounded-lg bg-[#2aa198]/10 border border-[#2aa198]/30 flex items-center justify-center text-[#2aa198]">
              <FileText className="w-3.5 h-3.5" />
            </div>
            <h2 className="text-base font-bold text-[#2b3638]">{t("repTitle")}</h2>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-[#edf5d3] text-[#859900] border border-[#cce38d] font-semibold">
              Signed by ReportAgent
            </span>
          </div>
          <p className="text-xs text-[#586e75]">
            {t("repSubtitle")}
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyMarkdown}
            className="px-3 py-1.5 rounded-lg bg-[#f5eed9] hover:bg-[#eee8d5] border border-[#dfd6bf] text-xs font-mono text-[#586e75] flex items-center gap-1.5 transition-colors cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-[#859900]" /> : <Copy className="w-3.5 h-3.5 text-[#2aa198]" />}
            <span>{copied ? (language === "zh" ? "已复制 Markdown" : "Copied Markdown") : (language === "zh" ? "复制 MD" : "Copy MD")}</span>
          </button>
          <button
            onClick={handleDownloadJson}
            className="px-3 py-1.5 rounded-lg bg-[#2aa198] hover:bg-[#238b83] text-white text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer shadow-xs"
          >
            <Download className="w-3.5 h-3.5" />
            <span>{t("repExportJson")}</span>
          </button>
        </div>
      </div>

      {/* Formal Printable Document Layout */}
      <div className="p-8 sm:p-10 rounded-2xl bg-[#fdfaf3] border border-[#dfd6bf] shadow-sm space-y-8 font-sans">
        {/* Document Title Header */}
        <div className="border-b border-[#dfd6bf] pb-6 flex flex-col sm:flex-row sm:items-end justify-between gap-4">
          <div>
            <span className="text-xs font-mono text-[#2aa198] uppercase tracking-wider font-semibold">
              VULNAGENT AUTONOMOUS SECURITY AUDIT
            </span>
            <h1 className="text-2xl font-bold text-[#2b3638] mt-1">
              {language === "zh" ? "软件安全审计与漏洞挖掘总报告" : "Audit Findings & Risk Assessment"}
            </h1>
            <p className="text-xs text-[#586e75] mt-1 font-mono">
              {language === "zh" ? "审计目标: " : "Target: "}<span className="text-[#2b3638] font-medium">{content.task.target.path || task.target.path}</span>
            </p>
          </div>

          <div className="text-left sm:text-right font-mono text-xs text-[#586e75]">
            <div>{language === "zh" ? "任务 ID: " : "Task: "}<span className="text-[#2aa198] font-semibold">{report.task_id}</span></div>
            <div>{language === "zh" ? "生成日期: " : "Generated: "}{new Date().toLocaleDateString()}</div>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold text-[#2b3638] uppercase tracking-wider font-mono flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-[#2aa198]" />
            {t("repExecutiveSummary")}
          </h3>
          <div className="p-5 rounded-xl bg-[#f5eed9] border border-[#dfd6bf] text-sm text-[#2b3638] leading-relaxed">
            {content.risk_summary.headline}
          </div>
        </div>

        {/* Severity & Metrics Scoreboard */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="p-4 rounded-xl bg-[#f5eed9] border border-[#dfd6bf]">
            <span className="text-[10px] uppercase font-mono text-[#586e75] block">
              {language === "zh" ? "评估候选总数" : "Total Evaluated"}
            </span>
            <span className="text-2xl font-bold font-mono text-[#2b3638] mt-1 block">
              {counts.total}
            </span>
          </div>
          <div className="p-4 rounded-xl bg-[#fce8e6] border border-[#f5b8b5]">
            <span className="text-[10px] uppercase font-mono text-[#dc322f] block">
              {language === "zh" ? "确认真实漏洞" : "Critical Confirmed"}
            </span>
            <span className="text-2xl font-bold font-mono text-[#dc322f] mt-1 block">
              {counts.confirmed}
            </span>
          </div>
          <div className="p-4 rounded-xl bg-[#edf5d3] border border-[#cce38d]">
            <span className="text-[10px] uppercase font-mono text-[#859900] block">
              {language === "zh" ? "复核剔除误报" : "False Positives Filtered"}
            </span>
            <span className="text-2xl font-bold font-mono text-[#859900] mt-1 block">
              {counts.rejected}
            </span>
          </div>
          <div className="p-4 rounded-xl bg-[#eef7f6] border border-[#bfe3e0]">
            <span className="text-[10px] uppercase font-mono text-[#2aa198] block">
              {language === "zh" ? "关联实证实体" : "Verified Evidence Count"}
            </span>
            <span className="text-2xl font-bold font-mono text-[#2aa198] mt-1 block">
              {content.summary.evidence_count}
            </span>
          </div>
        </div>

        {/* Confirmed Findings Section */}
        <div className="space-y-4">
          <h3 className="text-sm font-bold text-[#2b3638] uppercase tracking-wider font-mono flex items-center gap-2">
            <AlertOctagon className="w-4 h-4 text-[#dc322f]" />
            {t("repConfirmedFindings")}
          </h3>

          <div className="space-y-4">
            {reportFindings.map((f) => (
              <div
                key={f.vulnerability_id}
                className="p-5 rounded-xl bg-[#fcf8ed] border border-[#dfd6bf] space-y-3 shadow-2xs"
              >
                <div className="flex items-center justify-between gap-2 flex-wrap">
                  <div className="flex items-center gap-2">
                    <span className="px-2 py-0.5 rounded text-xs font-mono font-bold bg-[#fce8e6] text-[#dc322f] border border-[#f5b8b5]">
                      {f.severity || "CRITICAL"}
                    </span>
                    <span className="text-sm font-bold text-[#2b3638]">{f.title}</span>
                  </div>
                  <span className="font-mono text-xs text-[#2aa198] font-semibold">{f.cwe_id}</span>
                </div>

                <p className="text-xs text-[#586e75] leading-relaxed">{f.description}</p>

                {f.location && (
                  <div className="text-xs font-mono text-[#586e75] bg-[#f5eed9] p-2.5 rounded-lg border border-[#dfd6bf]">
                    {language === "zh" ? "漏洞位置: " : "Location: "}
                    <span className="text-[#2b3638] font-medium">{f.location.file_path}:{f.location.line_start}-{f.location.line_end}</span>
                    {f.location.function_name && <span> (fn: {f.location.function_name})</span>}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Strategic Remediation Section */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold text-[#2b3638] uppercase tracking-wider font-mono flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-[#859900]" />
            {t("repRemediationTitle")}
          </h3>

          <div className="space-y-2">
            {(recommendations.length ? recommendations : [
              language === "zh" ? "当前报告没有生成额外修复建议。" : "No additional remediation guidance was generated.",
            ]).map((rec, idx) => (
              <div
                key={idx}
                className="p-3.5 rounded-xl bg-[#f5eed9] border border-[#dfd6bf] flex items-start gap-3 text-xs text-[#2b3638] font-mono"
              >
                <span className="w-5 h-5 rounded-md bg-[#edf5d3] text-[#859900] border border-[#cce38d] flex items-center justify-center shrink-0 text-[11px] font-bold">
                  {idx + 1}
                </span>
                <span className="leading-relaxed">{rec}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
